# Generated by Django 3.1.3 on 2020-11-11 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ransomwares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('bitcoinaccount', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_id', models.CharField(max_length=30)),
                ('hostname', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('payments', 'Payments'), ('inProcess', 'InProcess'), ('successful', 'Successful'), ('unsuccessful', 'Unsuccessful')], default='inProcess', max_length=20)),
                ('ransomwares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ransomwares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
